before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
brews:
  - name: ipmon
    description: zero dependency ip address monitoring
    homepage: https://github.com/alxsad/ipmon
    license: "MIT"
    tap:
      owner: alxsad
      name: homebrew-ipmon
    commit_author:
      name: alxsad
      email: alxsad@gmail.com
    folder: Formula
